server:
  port: 8080
  compression:
    enabled: true
  http2:
    enabled: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: yvlrfkzdafqkoi
    password: 3ece757a5e74bad93a24af7f55f25e509c21de2c5e2878f34b13124566a6c099
    url: jdbc:postgresql://ec2-54-174-221-35.compute-1.amazonaws.com/dbonui0ra1v3hq